### ISSUE TITLE
My heading has an error at the top of the page 

### ISSUE THREAD

**Issue by NikaJT** [NikaJT/Tindog#1]
I have an error in the heading or beginning of the body of my code and cannot find the reason why. When you look at the web page you see a ( /> )at the top of my web page. I want the heading section to go all the way to the top of the page. I  cannot find where in my code this mistake is written. Can you please help me

**Comment by SAMEERAHMEDS** [comment]
Hey, check line number 28 you have added "/>", which is not necessary.  Just delete that line.

**Comment by NikaJT** [comment]
Thank You so much for your help. It is all corrected now.
